"""empty message

Revision ID: 8fee6e25a3cf
Revises: 1e70400de880
Create Date: 2024-08-08 22:40:18.574120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fee6e25a3cf'
down_revision = '1e70400de880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rep_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_angle', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('min_angle', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_exercise', schema=None) as batch_op:
        batch_op.drop_column('min_angle')
        batch_op.drop_column('max_angle')
        batch_op.drop_column('rep_number')

    # ### end Alembic commands ###
