"""empty message

Revision ID: 96e14040dc9c
Revises: 7c6bdb6c9bec
Create Date: 2024-08-17 21:24:04.993628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e14040dc9c'
down_revision = '7c6bdb6c9bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rep_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rep_goal')

    # ### end Alembic commands ###
