"""empty message

Revision ID: db7e79e94d6c
Revises: 08f7b83fdfbc
Create Date: 2024-08-20 21:44:39.961085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7e79e94d6c'
down_revision = '08f7b83fdfbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ex_goal', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ex_goal')

    # ### end Alembic commands ###
